<#Requires -Version 5.1
<#
.SYNOPSIS
  Transfera dev-hygiene cleaner — removes build artifacts and junk.

.DESCRIPTION
  Wipes everything that can be fully regenerated by the installer or run.py:
    • Python .venv  (re-created by run.py / Install-Transfera.ps1)
    • pip / uv caches
    • PyInstaller build/ and dist/ one-dirs
    • Frontend node_modules, dist/, Vite cache
    • Rust target/ incremental cache (the slow one — use -KeepRust to skip)
    • Staged sidecar bundle (frontend/src-tauri/resources/transfera-engine/)
    • pytest, ruff, mypy caches
    • Windows temp / __pycache__ trees
    • Log files inside backend/data/logs/  (NOT the DB, cache, or exports)

  DOES NOT TOUCH:
    • backend/data/db/         — your media database
    • backend/data/cache/      — thumbnail cache
    • backend/data/exports/    — generated reports
    • %APPDATA%\Transfera\     — installed-app data
    • Any destination folder outside the repo

  Usage:
    powershell -ExecutionPolicy Bypass -File scripts\Clean-Transfera.ps1
    powershell -ExecutionPolicy Bypass -File scripts\Clean-Transfera.ps1 -KeepRust
    powershell -ExecutionPolicy Bypass -File scripts\Clean-Transfera.ps1 -All

.PARAMETER KeepRust
  Skip wiping frontend/src-tauri/target/ (saves re-compiling Rust from scratch).
.PARAMETER All
  Also wipe backend/data/logs/, pip wheel cache, and npm cache.
.PARAMETER Yes
  Non-interactive — skip the confirmation prompt.
#>
[CmdletBinding()]
param(
  [switch]$KeepRust,
  [switch]$All,
  [switch]$Yes
)

$ErrorActionPreference = "Stop"

function Ok([string]$msg)   { Write-Host "  [OK] $msg"   -ForegroundColor Green  }
function Step([string]$msg) { Write-Host "`n==> $msg"     -ForegroundColor Cyan   }
function Warn([string]$msg) { Write-Host "  [WARN] $msg"  -ForegroundColor Yellow }
function Info([string]$msg) { Write-Host "  [--] $msg"    -ForegroundColor Gray   }

function Remove-Dir([string]$path, [string]$label) {
  if (Test-Path $path) {
    $size = "{0:N1} MB" -f ((Get-ChildItem $path -Recurse -File -ErrorAction SilentlyContinue |
      Measure-Object Length -Sum).Sum / 1MB)
    Remove-Item $path -Recurse -Force -ErrorAction SilentlyContinue
    Ok "Removed $label  ($size)"
  } else {
    Info "Already clean: $label"
  }
}

function Remove-Pattern([string]$root, [string]$pattern, [string]$label) {
  $items = Get-ChildItem $root -Filter $pattern -Recurse -Force -ErrorAction SilentlyContinue
  if ($items) {
    $count = ($items | Measure-Object).Count
    $items | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue
    Ok "Removed $count × $label"
  } else {
    Info "Already clean: $label"
  }
}

# ── Locate repo root ──────────────────────────────────────────────────────────
$Root = if ($PSScriptRoot -and (Test-Path (Join-Path $PSScriptRoot "..\run.py"))) {
  (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
} elseif (Test-Path "run.py") {
  (Get-Location).Path
} else {
  Write-Host "  [FAIL] Cannot find run.py. Run this from inside the Transfera repo." -ForegroundColor Red
  exit 1
}

Write-Host ""
Write-Host "  Transfera — Dev Hygiene Cleaner" -ForegroundColor Cyan
Write-Host "  Repo: $Root" -ForegroundColor DarkCyan
Write-Host ""

if (-not $Yes) {
  $ans = Read-Host "  This will delete all build artifacts in $Root. Continue? [Y/n]"
  if ($ans -ne "" -and $ans -notmatch "^[Yy]") { Write-Host "  Aborted."; exit 0 }
}

# ── Python build junk ─────────────────────────────────────────────────────────
Step "Python venv + caches"
Remove-Dir  (Join-Path $Root ".venv")          ".venv"
Remove-Dir  (Join-Path $Root "build")          "PyInstaller build/"
Remove-Dir  (Join-Path $Root "dist")           "PyInstaller dist/"
Remove-Pattern $Root "__pycache__"             "__pycache__ dirs"
Remove-Pattern $Root "*.pyc"                   "*.pyc bytecode"
Remove-Pattern $Root "*.pyo"                   "*.pyo bytecode"
Remove-Dir  (Join-Path $Root ".pytest_cache")  ".pytest_cache/"
Remove-Dir  (Join-Path $Root ".ruff_cache")    ".ruff_cache/"
Remove-Dir  (Join-Path $Root ".mypy_cache")    ".mypy_cache/"

# ── Frontend junk ─────────────────────────────────────────────────────────────
Step "Frontend artifacts"
Remove-Dir  (Join-Path $Root "frontend\node_modules")    "frontend/node_modules/"
Remove-Dir  (Join-Path $Root "frontend\dist")            "frontend/dist/"
Remove-Dir  (Join-Path $Root "frontend\.vite")           "frontend/.vite cache"
Remove-Dir  (Join-Path $Root "frontend\src-tauri\binaries") "staged sidecar binaries (legacy externalBin layout)"
$engineRes = Join-Path $Root "frontend\src-tauri\resources\transfera-engine"
if (Test-Path $engineRes) {
  Get-ChildItem $engineRes -Exclude ".gitkeep" -Force | Remove-Item -Recurse -Force
  Ok "cleared staged sidecar bundle (resources/transfera-engine/, kept .gitkeep)"
}
Remove-Pattern (Join-Path $Root "frontend\src-tauri\gen") "*.rs" "tauri gen/*.rs"

# ── Rust target ───────────────────────────────────────────────────────────────
Step "Rust target/"
if ($KeepRust) {
  Warn "Skipped (--KeepRust). Re-run without the flag to free ~2-10 GB."
} else {
  Remove-Dir (Join-Path $Root "frontend\src-tauri\target") "Rust target/ (~2-10 GB)"
}

# ── Logs (only logs, never DB/cache/exports) ──────────────────────────────────
Step "Log files"
$logDir = Join-Path $Root "backend\data\logs"
if ($All -and (Test-Path $logDir)) {
  Get-ChildItem $logDir -Filter "*.log" -File -ErrorAction SilentlyContinue | Remove-Item -Force
  Ok "Cleared *.log files in backend/data/logs/"
} else {
  Info "Skipped backend/data/logs/  (pass -All to include)"
}

# ── pip / npm caches (global, only with -All) ─────────────────────────────────
Step "Package manager caches"
if ($All) {
  $pipCache = Join-Path $env:LOCALAPPDATA "pip\cache"
  Remove-Dir $pipCache "pip wheel cache"
  npm cache clean --force 2>&1 | Out-Null
  Ok "npm cache cleared"
} else {
  Info "Skipped pip/npm caches (pass -All to include)"
}

# ── Summary ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "  ══════════════════════════════════════════════" -ForegroundColor Green
Write-Host "  ║  Clean complete. Untouched (your data):    ║" -ForegroundColor Green
Write-Host "  ║    backend/data/db/      (media database)  ║" -ForegroundColor Green
Write-Host "  ║    backend/data/cache/   (thumbnails)      ║" -ForegroundColor Green
Write-Host "  ║    backend/data/exports/ (reports)         ║" -ForegroundColor Green
Write-Host "  ║    %APPDATA%\Transfera\  (installed app)   ║" -ForegroundColor Green
Write-Host "  ║                                            ║" -ForegroundColor Green
Write-Host "  ║  To rebuild:  python run.py                ║" -ForegroundColor Green
Write-Host "  ║  Full install: scripts\Install-Transfera   ║" -ForegroundColor Green
Write-Host "  ══════════════════════════════════════════════" -ForegroundColor Green
Write-Host ""
